import {Header} from '@/shared/components/shared'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function CheckoutLayout({ children }: { children: ReactNode }) {
  return (
    <main className={'min-h-screen bg-[#F4F1EE]'}>
      <Header hasSearch={false} hasCart={false} className={'border-b-gray-200'}/>
      {children}
    </main>
  )
}
